### ISSUE TITLE
Make modules less brittle

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/lang#70]
Right now, with the introduction of #69, module source contents are added at a different time than the AST tree. This makes it difficult to reason about when modules are or aren't loaded. A better approach might be to have a way of inserting source contents on the fly as needed (and maybe even the same for AST). This would allow parts of the compiler to request source contents/AST and have it dynamically be computed/loaded if it hasn't already.

**Comment by kontheocharis** [comment]
Idea: Maybe it might be worth it to store Module objects inside modules instead of having N dashmaps for N fields.

**Comment by feds01** [comment]
I think it's just a simple matter of when the contents get moved into `Modules` before since a module might not even be inserted because it contains parse errors. What we should do is guarantee that the filename and source of the module is inserted before the ast gets inserted and then this issue should go away
